// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-expenses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_expenses_default = defineTool({
  name: "list_expenses",
  title: "List expenses",
  description: "List the signed-in user's expenses, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 20)."),
    category: z.string().optional().describe("Filter by exact category name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("expenses").select("id, amount, category, merchant, name, description, occurred_at, source").eq("user_id", ctx.getUserId()).order("occurred_at", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { expenses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-expense.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_expense_default = defineTool2({
  name: "create_expense",
  title: "Create expense",
  description: "Create a new expense entry for the signed-in user.",
  inputSchema: {
    amount: z2.number().positive().describe("Expense amount (positive number)."),
    category: z2.string().trim().min(1).describe("Category name, e.g. 'alimenta\xE7\xE3o'."),
    merchant: z2.string().trim().optional().describe("Merchant / store name."),
    description: z2.string().trim().optional().describe("Free-form note."),
    occurred_at: z2.string().optional().describe("ISO timestamp when the expense occurred. Defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ amount, category, merchant, description, occurred_at }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("expenses").insert({
      user_id: ctx.getUserId(),
      amount,
      category,
      merchant,
      description,
      occurred_at: occurred_at ?? (/* @__PURE__ */ new Date()).toISOString(),
      source: "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Expense created: ${data.id}` }],
      structuredContent: { expense: data }
    };
  }
});

// src/lib/mcp/tools/monthly-summary.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var monthly_summary_default = defineTool3({
  name: "monthly_summary",
  title: "Monthly expense summary",
  description: "Return total spend and per-category breakdown for a given month (defaults to current).",
  inputSchema: {
    year: z3.number().int().min(2e3).max(2100).optional(),
    month: z3.number().int().min(1).max(12).optional().describe("1-12")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, month }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const now = /* @__PURE__ */ new Date();
    const y = year ?? now.getUTCFullYear();
    const m = month ?? now.getUTCMonth() + 1;
    const start = new Date(Date.UTC(y, m - 1, 1)).toISOString();
    const end = new Date(Date.UTC(y, m, 1)).toISOString();
    const { data, error } = await supabaseForUser3(ctx).from("expenses").select("amount, category").eq("user_id", ctx.getUserId()).gte("occurred_at", start).lt("occurred_at", end);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byCategory = {};
    let total = 0;
    for (const row of data ?? []) {
      const amt = Number(row.amount) || 0;
      total += amt;
      byCategory[row.category] = (byCategory[row.category] ?? 0) + amt;
    }
    const summary = { year: y, month: m, total, byCategory };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lxlsrnysjtojnlhvjjew";
var mcp_default = defineMcp({
  name: "organizze-mcp",
  title: "Organizze",
  version: "0.1.0",
  instructions: "Tools for the Organizze personal-finance app. Use `list_expenses` to read the signed-in user's expenses, `create_expense` to add a new one, and `monthly_summary` for totals by category.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_expenses_default, create_expense_default, monthly_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
